### ISSUE TITLE
Final Review

### ISSUE THREAD

**Issue by kcrisci94** [imcdonald1/rockClimbingInsights#8]
# Summary

*This project investigated the data logged by serious climbers throughout the world, who have completed difficult climbs and logged their results, specifically the steepness of the climb. Using this information, it was able to be determined that weight, sex and experience have the highest impact on the level of difficulty a climber has accomplished. It was also discovered that a persons height does not have much of an effect on the difficulty level of climbs that the person is able to do. The next planned step is to incorporate this model to make predictions based on specific climbing routes in order to help climbers make safe, and informed decisions on which routes they have the ability to take.*

# Data Preparation

*In part 1, data was pulled into four different tables from an online database. These four tables allowed for the data to be placed in a "Tidy" manner, and missing values were replaced with NA, which was good. In part 2, the data was entered using a provided .csv file. The data appears to be tidy, and provides good support for the original dataset in part 1. For both part 1 and part 2 however, I would suggest after each change to your table, you use head(TABLENAME) in order to show the first 5 rows of your tables, so that users can get a better idea of exactly what is happening. However, the portfolio appears to have tidy and cleaned data. *

# Modeling

*A model was created that would predict the highest difficulty of a climb that a person could do based on several factors such as height, weight, date started climbing (experience), and sex. The dependent variable in this model is the grade-id, or the specific level of the grade. The purpose of this model is clearly stated as well. The portfolio accurately interprets the information that is discussed, but I recommend discussing other things that the model shows, such as the R squared values and the coefficients. *

# Validation

*The portfolio includes a model that has been tested using training and testing. My only suggestion in this phase would be to describe exactly what the number is telling us that is returned by the RMSE function. *
 

# R Proficiency

*The R code is easy to understand and easy to follow. Some of the code could be improved and shortened using the %>% (piping) from the dplyr library, but it's not entirely necessary. I found no coding errors. *

# Communication

*Having no experience in serious climbing myself, I can say that I am able to fully understand what is going on, which is good. Visualizations are used effectively, and make it easier to interpret the results. There are a few locations that have misspelled words and a few typos, but generally, it is really good. A specific typo that I would fix is in part 2 when you load in your data from part 1, you say that you're loading the "musicinsights.Rmd" file instead of your part 1 file.*

# Critical Thinking

*The portfolio provides details about where this study could go in the future and how it could be used, for example, to determine which routes are unsafe or beyond what a climber is able to accomplish. One unintended consequence that was not discussed is that having all this data telling an individual climber that they don't have the skill or physical build for a specific climb might empower them to attempt it anyway to prove the system wrong, and then end up getting injured or killed for attempting something beyond their level. *

**Comment by imcdonald1** [comment]
# Data Preparation and Modeling (*your score* out of 20%)
18/20
The data was cleaned well, but additional data could have been excluded from tables, as it was not used in this project. The models were effective and showed the results well. The results could have been explained better however.

# Validation and Operationalization (*your score* out of 20%)
18/20
The model was validated and the idea for operationalization was good. The consequences and social implications were also explained well.
# R Proficiency (*your score* out of 20%)
17/20
The R code used  functional programming effectively and the code was fairly easy to read, but the readability and reproducibility could have been improved.
# Communication (*your score* out of 20%)
19/20
Things were communicated effectively enough for my peer review to gain the major takeaways from my project. However I still feel that I could have explained certain things better to make the person understand even more about climbing. 
# Critical Thinking (*your score* out of 20%)
18/20
I thought of many of the outcome and unintended consequences that are often already discussed in climbing communities, however I didn't think of some that my peer review brought up. This leads me to think there could be even more I am missing, however I describe several quite well.
